### PR TITLE
(WIP) Manifest version 3 port

### PR DESCRIPTION
**Pull request by khaled-0**

### CODE REVIEW

**Comment by khaled-0** [comment]
Context menu link capturing fixed
image

**Comment by khaled-0** [comment]
Extension works for the most part now
BUT, https://github.com/ugetdm/uget-integrator/issues/108

**Comment by khaled-0** [comment]
Hey, I've tested on chromiun, chrome, firefox, brave, vivaldi
Everything seems to work fine.

**Comment by alireza-amirsamimi** [comment]
If Persepolis uses intermediate script, every thing work fine.
But if Persepolis is not already running and this add-ons call Persepolis directly(not with intermediate shell), Persepolis runs for a few seconds and then immediately crashes. 
Persepolis use intermediate shell script in Linux and BSD and Mac OS X now. So every thing is good on Linux, BSD and Mac OS x. But we have the mentioned problem in Windows. 
Please checkout this [link](https://stackoverflow.com/questions/49180342/webextensions-native-messaging-shuts-down-targeted-application-too-quickly). Somebody suggest solution.

**Comment by JafarAkhondali** [comment]
Thank you @khaled-0 for your work,
I have an issue with my system that's why it took so long to merge.

**Pull request merged**
